# Generated by Django 2.0.2 on 2018-02-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoAnother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('todo', models.ForeignKey(on_delete=True, to='todo.Todo')),
            ],
        ),
        migrations.CreateModel(
            name='TodoYetAnother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('todo', models.ForeignKey(on_delete=True, to='todo.TodoAnother')),
            ],
        ),
    ]
