# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoanother_todoyetanother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoanother',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Todo'),
        ),
        migrations.AlterField(
            model_name='todoyetanother',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.TodoAnother'),
        ),
    ]
